



export enum BigFiveModelType{
    OPENNESS = "OPENNESS",
    CONSCIENTIOUSNESS = "CONSCIENTIOUSNESS",
    EXTRAVERSION = "EXTRAVERSION",
    AGREEABLENESS = "AGREEABLENESS",
    NEUROTICISM = "NEUROTICISM",
}