


export enum PersonalityType{
    INTROVERT = "INTROVERT",
    EXTROVERT = "EXTROVERT",
    CREATIVE = "CREATIVE",
    REALISTIC = "REALISTIC",
    EMPATHIC = "EMPATHIC",
    OPTIMISTIC = "OPTIMISTIC",
    PESSIMISTIC = "PESSIMISTIC",
    SPONTANEOUS = "SPONTANEOUS",
    ORGANIZED = "ORGANIZED",
    AMBITIOUS = "AMBITIOUS",
    CURIOUS = "CURIOUS",
    ADVENTUROUS = "ADVENTUROUS",
    OBSERVANT = "OBSERVANT",
    FUNNY = "FUNNY",
    CONFIDENT = "CONFIDENT",
}